name: '.npmrc auth tokens'
author: digitalvisioncz
description: 'Add private repositories'' auth tokens to .npmrc'
inputs:
  token:
    description: 'Access token'
    required: true
  registryUrl:
    description: 'URL of the registry (without `https://`'
    required: true

runs:
  using: 'composite'
  steps:
    - run: echo "Creating .npmrc"
      shell: bash
    - run: echo "//${{ inputs.registryUrl }}/:_authToken=${{ inputs.token }}" >> ./.npmrc
      shell: bash
    - run: cat ./.npmrc
      shell: bash
branding:
  icon: package
  color: yellow